Corrección de la entrega:

.....FFFF.....
======================================================================
FAIL: test_lista_vacia (tests.test_semana_02.TestInvertirLista)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 22, in test_lista_vacia
    self.assertEqual(semana_02.invertir_lista([]), [])
AssertionError: None != []

======================================================================
FAIL: test_numeros (tests.test_semana_02.TestInvertirLista)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 13, in test_numeros
    self.assertEqual(semana_02.invertir_lista([1, 2, 3, 4, 5]), [5, 4, 3, 2, 1])
AssertionError: None != [5, 4, 3, 2, 1]

======================================================================
FAIL: test_strings (tests.test_semana_02.TestInvertirLista)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 17, in test_strings
    self.assertEqual(semana_02.invertir_lista(["Bogotá", "Rosario", "San Fernando", "San Miguel"]),
AssertionError: None != ['San Miguel', 'San Fernando', 'Rosario', 'Bogotá']

======================================================================
FAIL: test_un_elemento (tests.test_semana_02.TestInvertirLista)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlopez/.local/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/mlopez/git/homework-checker/01_getting_data/tests/test_semana_02.py", line 26, in test_un_elemento
    self.assertEqual(semana_02.invertir_lista([42]), [42])
AssertionError: None != [42]

----------------------------------------------------------------------
Ran 14 tests in 0.002s

FAILED (failures=4)

